site_name: Data science
site_author: Digital Education Service
copyright: Copyright © Digital Education Service | University of Leeds

nav:
    - Welcome: index.md
    - Unit 1:
        - '1. What is data science?': content/unit1/01_01_what-is-data-science.md
        - '2. The data, its quality and its structure': content/unit1/01_02_the_data_its_quality_and_its_structure.md
        - '3. Data preparation': content/unit1/01_03_data_preparation.md
        - '4. Data visualisation': content/unit1/01_04_data_visualisation.md
        - '5. Unit references': content/unit1/01_06_unit_references.md
    - Unit 2:
        - 'Introduction': content/unit2/02_00_classification.md
        - '1. Decision trees':
            - '1a. Decision trees': content/unit2/02_01_decision_trees.md
            - '1b. Decision tree training': content/unit2/02_02_DT_training.md
            - '1c. DT training on a vertebrate dataset': content/unit2/02_03_DT_vertebrate.md
        - '2. Measuring the performance of a classification model': content/unit2/02_04_measuring_performance.md
        - '3. Overfitting, underfitting and generalisation': content/unit2/02_05_overfitting_underfitting.md
        - '4. References': content/unit2/02_06_unit_references.md
    - Unit 3:
        - 'Clustering and classification in algorithms': content/unit3/03_00_clustering_classification.md
        - '1. Clustering':
            - '1. Introduction': content/unit3/03_01_clustering_introduction.md
            - '1a. Two clusters case': content/unit3/03_01a_two_clusters.md
            - '1b. General case multi clusters: K-means algorithm': content/unit3/03_01b_general_case_multi_K.md
            - '1c. Clusters loss function: measuring the quality of the cluster': content/unit3/03_01c_clusters_loss_function.md
            - '1d. Specifying K through elbow method': content/unit3/03_01d_specifying_K_through.md
            - '1e. Initialising the centroids': content/unit3/03_01e_initialising_centroids.md
            - '1f. Mini-batch K means++': content/unit3/03_01f_mini_batch_K.md
            - '1g. Bisecting K-means algorithm': content/unit3/03_01g_bisecting_K_means.md
            - '1h. Lesson summary': content/unit3/03_01h_clustering_summary.md
        - '2. Basic numerical distance-based classification':
            - '2a. Introduction': content/unit3/03_02a_intro_basic_numerical_classification.md
            - '2b. Lazy classification': content/unit3/03_02b_lazy_classification.md
            - '2c. K-nearest neighbour algorithm': content/unit3/03_02c_K_nearest.md
            - '2d. Choosing best k': content/unit3/03_02d_choosing_best_k.md
            - '2e. Lesson summary': content/unit3/03_02e_classification_summary.md
        - '3. Ensemble methods': content/unit3/03_03_ensemble_methods.md
        - '4. References': content/unit3/03_04_unit_references.md
    - Unit 4:
        - 'Linear and non linear regression': content/unit4/04_00_regression_classification.md
        - '1. Simple Linear Regression Models':
            - '1a. Simple linear regression models': content/unit4/04_01a_linear_regression_models.md
            - '1b. Example of linear regression models': content/unit4/04_01b_example_linear_regression.md
            - '1c. Loss, objective, error or cost function for regression': content/unit4/04_01c_loss_error_cos_function.md
            - '1d. Simple linear model exercise': content/unit4/04_01d_simple_linear_model_exercise.md
            - '1e. Approximate solutions - gradient descent': content/unit4/04_01e_Gradient_decent.md
            - '1f. Evaluating a regression model via R2 and the RMSE': content/unit4/04_01f_sgd_exercises.md
        - '2. Linear regression with linear and non-linear basis functions':
            - '2a. Linear regression with linear and non-linear basis functions': content/unit4/04_02a_linear_regression_basis_functions.md
            - '2b. Basis functions': content/unit4/04_02b_basis_functions.md
            - '2c. Linear basis model exercise': content/unit4/04_02c_linear_basis_model_exercise.md
            - '2d. Batch learning': content/unit4/04_02d_Batch_learning.md
            - '2e. Implementing a stochastic gradient descent with gaussian basis': content/unit4/04_02e_linear_regression_training.md
            - '2f. Regression models': content/unit4/04_02f_regression_models.md
            - '2g. Regularisation exercise': content/unit4/04_02g_least_squares_with_basis.md
            - '2h. Linear regression models': content/unit4/04_02h_linear_regression_models.md
            - '2i. Preventing overfitting the data and overshooting the loss minimum': content/unit4/04_02i_preventing_overfitting.md
        - '3. Non-linear regression via neural networks': content/unit4/04_03a_multi_layer_multi_output.md
        - '4. Learning from a probabilistic perspective': content/unit4/04_4_learning_from_probabilistic_perspective.md
        - '5. Unit summary': content/unit4/04_05_unit_summary.md
        - '6. References': content/unit4/04_06_unit_references.md
    - Unit 5:
        - '1. Linear and non-Linear classification': content/unit5/05_01_linear-non-linear-classification.md
        - '2. Linear model for classification': content/unit5/05_02_linear-model-for-classification.md
        - '3. Binary classification: The perception': content/unit5/05_03_binary-classification-perception.md
        - '4. Binary classification: Logistic regression':  content/unit5/05_04_binary-classification-logistic-regression.md
        - '5. Multi-class problems':  content/unit5/05_05_multi-class-problems.md
        - '8. Unit references':  content/unit5/05_08_unit_references.md

theme:
  name: material
  custom_dir: overrides
  features:
    - navigation.tabs
  font:
    text: Inter
  favicon: img/favicon.jpg

plugins:
  - search

markdown_extensions:
  - attr_list
  - admonition
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.tabbed
  - pymdownx.superfences
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.snippets
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.caret
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.smartsymbols
  - pymdownx.betterem:
      smart_enable: all


extra_javascript:
  - javascript/tablecontentsoverride.js
  - javascript/config.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

extra_css:
  - css/extra.css
